title: Chris Kreienkamp
theme: jekyll-theme-minimal

author:
  avatar           : /assets/headshot_circle.png
  bio              : "Self-Driving Car Engineer"
  email            : "cjkreienkamp@gmail.com"
  github           : "cjkreienkamp"
